dist: trusty
sudo: required
language: c++
compiler:
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install qt5-qmake
  - sudo apt-get install libqt5core5a
  - sudo apt-get install libqt5*
  - $(dpkg -L qt5-qmake | grep /bin/) -query

script:
  - $(dpkg -L qt5-qmake | grep /bin/) apk_deeplink_extractor.pro
  - make